# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
# APPLY_FIXES: all
ENABLE:
  - BASH
  - DOCKER
  - MARKDOWN
  - YAML
  - ACTION
  - REPOSITORY
DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - REPOSITORY_DEVSKIM
YAML_FILTER_REGEX_EXCLUDE: '(docker-compose.yml)'
BASH_SHELLCHECK_ARGUMENTS: '-S warning'
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
GITHUB_STATUS_REPORTER: false
