# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
APPLY_FIXES:
  - BASH_SHFMT
ENABLE:
  - BASH
  - DOCKERFILE
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - YAML
ENABLE_LINTERS:
  - JAVASCRIPT_PRETTIER

FILTER_REGEX_EXCLUDE: '(pnpm-lock.yaml|pnpm-workspace.yaml)'
EXCLUDED_DIRECTORIES: ['megalinter-reports', 'node_modules']

BASH_SHELLCHECK_ARGUMENTS: '-S warning'
BASH_SHFMT_ARGUMENTS: '--case-indent --indent 2 --space-redirects --language-dialect bash'
JSON_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
JAVASCRIPT_DEFAULT_STYLE: 'prettier'
JAVASCRIPT_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'

CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false
MARKDOWN_SUMMARY_REPORTER: true
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
