name: "mongodb-backup"
version: "3.7"
services:

  # DB: MongoDB
  mongo-db:
    container_name: backup-mongo-db
    image: mongo:6.0.6
    restart: no
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongodump.sh:/tmp/mongodump.sh
      - mongodb-data:/data/db
    # // NOTE:  using entrypoint script would supercede mongodb init scripts
    # entrypoint: [ "/bin/sh", "/tmp/mongodump.sh" ]
    security_opt:
      - no-new-privileges
    secrets:
      - MONGODB_USER
      - MONGODB_PASSWORD

volumes:
  mongodb-data:
    name: mongodb-data
    external: true

secrets:
  MONGODB_USER:
    file: ./.env
  MONGODB_PASSWORD:
    file: ./.env
