name: 'mongo-backup'
version: '3.7'
services:
  # DB: MongoDB
  mongo:
    container_name: ${MONGO_CONTAINER}
    image: mongo:8.0.10
    restart: no
    env_file:
      - ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongodump.sh:/tmp/mongodump.sh:ro
      - mongodb-data:/data/db
    security_opt:
      - no-new-privileges
    secrets:
      - mongo_user_service
      - mongo_password_service

volumes:
  mongo-data:
    name: mongo-data
    external: true

secrets:
  mongo_user_service:
    file: ${SECRET_PATH}/.secret.mongo_user_service.txt
  mongo_password_service:
    file: ${SECRET_PATH}/.secret.mongo_password_service.txt
